// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoObph-Avzj4NtaasNjUXOVffLtZ6lRrc',
    appId: '1:159426030277:ios:a1b214b840e32f72325eac',
    messagingSenderId: '159426030277',
    projectId: 'listacontatos-55d72',
    storageBucket: 'listacontatos-55d72.appspot.com',
    iosBundleId: 'br.com.cristianbrunone.listaContatos',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoObph-Avzj4NtaasNjUXOVffLtZ6lRrc',
    appId: '1:159426030277:android:e3bd54fcb520faa1325eac',
    messagingSenderId: '159426030277',
    projectId: 'listacontatos-55d72',
    storageBucket: 'listacontatos-55d72.appspot.com',
  );
}
